first commit for lesson 3
KuznetsovVlads/Lesson-1 pull request #2
Opened 2023-03-30 18:09 UTC by KuznetsovVlads

Вроде как выполнил задание, но кажется нужно переписать взаимодействие класса Station с Train

2023-04-11 20:56 UTC, d1ma-angel requested changes

2023-04-11 20:56 UTC, d1ma-angel commented on App/route.rb
> +        @start = start
А зачем тебе стартовая и конечная станция отдельными переменными? Ты же всегда можешь их достать из списка станций. Если где-то будут нужны, то лучше просто создать для этого методы.

2023-04-11 20:56 UTC, d1ma-angel commented on App/route.rb
> +            index_finish = @list_stations.index(@finish)
Лучше просто .size и вставить в зависимости от длины массива. index очень тяжеловесный метод.

2023-04-11 20:56 UTC, d1ma-angel commented on App/route.rb
> +          elsif @list_stations.include?(station)
Смотри, ты тут и в 11 строке выполняешь одни и те же действия. Это мгновенный сигнал, что такое нужно вынести в отдельный метод.

2023-04-11 20:56 UTC, d1ma-angel commented on App/route.rb
> +    def see_list
Ты уверен, что это работает?

2023-04-11 20:56 UTC, d1ma-angel commented on App/station.rb
> +    def trains
Лучше просто создать attr_reader

2023-04-11 20:56 UTC, d1ma-angel commented on App/train.rb
> +    def where_i_am
Смотри, несколько моментов:
1) Обрати внимание, ты строку 65 применяешь много раз по классу - сразу индикатор - нужно выносить в метод
2) Лучше этот метод разделить на 3 разных: previous_station, current_station, next_station
3) Сразу подскажу тебе хорошую практику - лучше всегда делить между собой логики отображения и модели. К чему я это. Лучше, чтобы методы модели возвращали именно объект, а не какой-то текст в консоль выводили. Тогда они становятся особенно полезными. А уже вывести в консоль ты сможешь потом ну уровне отображения - увидишь у тебя появится меня в следующем задании.

2023-04-11 20:56 UTC, d1ma-angel commented on App/train.rb
> +    def add_wagon
Не проверяешь, что поезд стоит

2023-04-11 20:56 UTC, d1ma-angel commented on App/train.rb
> +    def assign_route(route)
Не ставишь паровоз на 1 станцию в маршруте. Станция об этом ничего не знает, а хочется сделать station.trains и увидеть этот паровозик там.

2023-04-11 20:56 UTC, d1ma-angel commented on App/train.rb
> +    def go_to_next_station
То же самое как к 36 строке

2023-04-11 20:56 UTC, d1ma-angel commented on App/train.rb
> +end
Общая рекомендация - не надо путсов. Лучше уже в меню будешь оповещать пользователя (след урок). Да, я понимаю, что в задании об этом не говорили, но т.к. у тебя уже есть опыт лучше сразу буду учить тебя красивее, чтобы потом ты не переучивался.

2023-04-17 13:15 UTC, KuznetsovVlads commented on App/route.rb
> +        @start = start
Показалось, что так прописано в условии. Но действительно эти станции легко найти в массиве.

2023-04-17 13:18 UTC, KuznetsovVlads commented on App/route.rb
> +            index_finish = @list_stations.index(@finish)
Не знал про это.  Я долго не мог понять как добавить новый элемент не в начало и не в конец массива. 
Сейчас понял, что можно просто добавлять элемент с индексом [-2] как предпоследний элемент

2023-04-17 13:19 UTC, KuznetsovVlads commented on App/route.rb
> +          elsif @list_stations.include?(station)
Постараюсь запомнить и применять этот подход.

2023-04-17 13:20 UTC, KuznetsovVlads commented on App/route.rb
> +    def see_list
проверил, работает. 
see_list  Выводит информацию в таком виде: Lviv -> Ternopil -> Kherson -> Odesa
Или ты что-то другое имел ввиду?

2023-04-18 13:04 UTC, d1ma-angel requested changes

2023-04-18 13:04 UTC, d1ma-angel commented on App/train.rb
> +        @amount_wagons -= 1 if @amount_wagons > 1 && @speed.zero?
`if @amount_wagons > 0`

2023-04-18 13:04 UTC, d1ma-angel commented on App/train.rb
> +            @current_station = @route.list_stations[index_current_station + 1] # Переходим на следующую станцию
Хм, обрати внимание на свой метод `next_station`. Ничего не напоминает? Примени)

2023-04-18 13:04 UTC, d1ma-angel commented on App/train.rb
> +            @current_station = @route.list_stations[index_current_station - 1]
Хм, обрати внимание на свой метод `previous_station`. Ничего не напоминает? Примени)

2023-04-18 13:04 UTC, d1ma-angel commented on App/station.rb
> +    def send_train(train)
Не очень понял этот метод

2023-04-18 13:04 UTC, d1ma-angel commented on App/station.rb
> +    def trains_by_type(type)
Список, не количество) Ну и, в идеале, возвращать именно массив самих объектов

2023-04-18 13:04 UTC, d1ma-angel commented on App/station.rb
> +        puts list_trains.join(", ")
Лучше возвращать массив объектов. А за красивое отображение будет отвечать отдельный метод. В целом метод возвращающий список поездов у тебя есть.

2023-04-18 13:04 UTC, d1ma-angel commented on App/station.rb
> +    attr_accessor :trains
А почему `attr_accessor`?

2023-04-20 15:23 UTC, merged