Added new files: main, wagon, train_cargo, train_pass, wagon_cargo, w…
KuznetsovVlads/Lesson-1 pull request #3
Opened 2023-04-30 18:07 UTC by KuznetsovVlads

…agon_pass

2023-05-01 09:37 UTC, d1ma-angel requested changes

2023-05-01 09:37 UTC, d1ma-angel commented on App/route.rb
>      puts info_list.join(' -> ')
Не ошибка, просто покажу красивый вариант
`@list_stations.map(&:name).join(' -> ')`

2023-05-01 09:37 UTC, d1ma-angel commented on App/main.rb
> +    case @answer = gets.to_i # answer from user
1) Чтобы каждую строку не писать clear и потом в случае изменений файла о нем не забыть лучше так:
```
answer = gets.to_i
clear
case answer
...
```
2) И да, не очень понял почему это инстанс-переменная.

2023-05-01 09:37 UTC, d1ma-angel commented on App/main.rb
> +      if stations.size < 2
Чище было бы все равно вызывать `create_route`, а уже в нем проверять на количество станций

2023-05-01 09:37 UTC, d1ma-angel commented on App/main.rb
> +      creat
)) `create` с `e` на конце

2023-05-01 09:37 UTC, d1ma-angel commented on App/main.rb
> +require_relative 'route'
Создай файлик, который позволил бы просто сделать `ruby app.rb` для того, чтобы полностью запустить программу. За то, что выделил механизм меню в отдельный класс похвала

2023-05-01 09:37 UTC, d1ma-angel commented on App/main.rb
> +    case @answer = gets.to_i #answer_from_user
У тебя очень повторяется цепочка логики, лучше такое выносить.
1) Спросил про тип поезда, положил в переменную ответ
2) Не заходя в ветвление узнал номер поезда
3) Проверил, что номер адекватный
4) Создал поезд нужного типа согласно ответа из пункта 1

2023-05-01 09:37 UTC, d1ma-angel commented on App/train_cargo.rb
> +class TrainCargo < Train
А вот это уже важное замечание. У тебя уже есть класс поезда. Всеми силами старайся не дублировать информацию. О чем тут я: у тебя есть и класс ГрузовойПоезд и инстанс переменная тип. Это дублирование. Ты вынужден будешь по всему приложению контролировать уже 2 переменные. А представь, что с тобой работает группа разрабов и большинство решит, что, чтобы переделать поезд из грузового в пассажирский будет достаточно изменить класс и у тебя возникнет такое понятие как "Неконсистентность". Как будет вести себя во всех методов в этом случае приложение никто предугадать не сможет. В общем твоя задача избавиться от инстанс переменной @type. И да, это нормально, у меня еще не было ни одного ученика, кто сам догадался бы это сделать.

2023-05-05 09:00 UTC, d1ma-angel requested changes

2023-05-05 09:00 UTC, d1ma-angel commented on App/route.rb
> +    @list_stations.delete(station)
Тут слишком многое разрешил. Позволишь удалить и конечные

2023-05-05 09:00 UTC, d1ma-angel commented on App/route.rb
> -    if station_include?(station)
И эта проверка тоже нужна иначе может случиться так, что ты добавишь в середину станцию, которая также является и конечной и тогда не сможешь ее удалить.

2023-05-05 09:00 UTC, d1ma-angel commented on App/train.rb
> +  def go_to_previous_station
Я не говорю, что нужно оповещать пользователя если он делает какую-то ерунду. Но ему точно нельзя разрешить ее сделать. Пытаешься переместить поезд на станцию раньше начальной. То же самое касается и конечной. Ты чуть позже познакомишься с валидациями и исключениями. Там тебе подскажут как такое обрабатывать.

2023-05-05 09:00 UTC, d1ma-angel commented on App/railroad.rb
> +require_relative 'route'
Это мелочь и мало кто об этом говорит, но лучше если видишь require_relative (relative - относительный) писать именно относительный путь (относительно текущей директории) `'./route'`
Тогда код будет легко читаться
`require 'some_library'` какая-то библиотека написанная не тобой
`require_relative '../folder/file'` твой файл

2023-05-05 09:00 UTC, d1ma-angel commented on App/railroad.rb
> +  def find_wagon_by_type(train)
Смотри, да, я понимаю, что это будет работать, но нужно учиться отделять слои логики/бизнеса/моделей от отображения. Тебе нужно как минимум на уровне моделей не допустить прикрепления вагонов не того типа.

2023-05-05 17:47 UTC, KuznetsovVlads commented on App/railroad.rb
> +require_relative 'route'
А я думал что require - это абсолютный путь и нужно указывать точный путь и расширение файла.
А require_relative - это относительный путь и программа сама найдет файл (сахар - Ruby)

2023-05-09 08:50 UTC, merged